In [1]:
import pandas as pd
from pathlib import Path
import datetime as dt
import numpy as np

In [2]:
#Import Raw Median Income by County data
fl_raw_18_df = pd.read_csv(Path("../../../../data/raw_data/median_income/ACSST5Y2018.S1903-2024-09-04T005331.csv"))
fl_raw_19_df = pd.read_csv(Path("../../../../data/raw_data/median_income/ACSST5Y2019.S1903-2024-09-04T005419.csv"))
fl_raw_20_df = pd.read_csv(Path("../../../../data/raw_data/median_income/ACSST5Y2020.S1903-2024-09-04T005442.csv"))
fl_raw_21_df = pd.read_csv(Path("../../../../data/raw_data/median_income/ACSST5Y2021.S1903-2024-09-04T005457.csv"))

**2018 Data**

In [4]:
#2018 Data
print("Shape:",fl_raw_18_df.shape)
display(fl_raw_18_df.columns)
display(fl_raw_18_df.head(10))

Shape: (469, 2)

Index(['Label (Grouping)', 'HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households'], dtype='object')

,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households
0,"Alachua County, Florida",NaN
1,Number,NaN
2,Estimate,"97,048"
3,Percent Distribution,NaN
4,Estimate,"97,048"
5,Median income (dollars),NaN
6,Estimate,"49,078"
7,"Baker County, Florida",NaN
8,Number,NaN
9,Estimate,"8,625"

In [5]:
#Rename 2018 Columns
fl_18_df = fl_raw_18_df.rename(columns={"Label (Grouping)":"County","HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households":"2018 Median Income"})
fl_18_df.head(20)

                         County 2018 Median Income
0       Alachua County, Florida                NaN
1                        Number                NaN
2                      Estimate             97,048
3          Percent Distribution                NaN
4                      Estimate             97,048
5       Median income (dollars)                NaN
6                      Estimate             49,078
7         Baker County, Florida                NaN
8                        Number                NaN
9                      Estimate              8,625
10         Percent Distribution                NaN
11                     Estimate              8,625
12      Median income (dollars)                NaN
13                     Estimate             61,769
14          Bay County, Florida                NaN
15                       Number                NaN
16                     Estimate             70,199
17         Percent Distribution                NaN
18                     Estimate             70,199
19      Median income (dollars)                NaN

In [6]:
#Moving County names
fl_18_df['county'] = fl_18_df['County'].where(fl_18_df['County'].str.contains('County'))

fl_18_df['county'] = fl_18_df['county'].ffill()

fl_18_df = fl_18_df.loc[~fl_18_df['County'].str.contains('County')]

fl_18_df.head(15)

                         County 2018 Median Income                   county
1                        Number                NaN  Alachua County, Florida
2                      Estimate             97,048  Alachua County, Florida
3          Percent Distribution                NaN  Alachua County, Florida
4                      Estimate             97,048  Alachua County, Florida
5       Median income (dollars)                NaN  Alachua County, Florida
6                      Estimate             49,078  Alachua County, Florida
8                        Number                NaN    Baker County, Florida
9                      Estimate              8,625    Baker County, Florida
10         Percent Distribution                NaN    Baker County, Florida
11                     Estimate              8,625    Baker County, Florida
12      Median income (dollars)                NaN    Baker County, Florida
13                     Estimate             61,769    Baker County, Florida
15                       Number                NaN      Bay County, Florida
16                     Estimate             70,199      Bay County, Florida
17         Percent Distribution                NaN      Bay County, Florida

In [7]:
#Moving values
filter_number = fl_18_df["County"].str.contains("Number")

filter_num_true = filter_number.loc[filter_number].index

filter_num_plus = filter_number.loc[filter_number].index+1

value = fl_18_df.loc[filter_num_plus,["2018 Median Income"]]

fl_18_df.head(15)

                         County 2018 Median Income                   county
1                        Number                NaN  Alachua County, Florida
2                      Estimate             97,048  Alachua County, Florida
3          Percent Distribution                NaN  Alachua County, Florida
4                      Estimate             97,048  Alachua County, Florida
5       Median income (dollars)                NaN  Alachua County, Florida
6                      Estimate             49,078  Alachua County, Florida
8                        Number                NaN    Baker County, Florida
9                      Estimate              8,625    Baker County, Florida
10         Percent Distribution                NaN    Baker County, Florida
11                     Estimate              8,625    Baker County, Florida
12      Median income (dollars)                NaN    Baker County, Florida
13                     Estimate             61,769    Baker County, Florida
15                       Number                NaN      Bay County, Florida
16                     Estimate             70,199      Bay County, Florida
17         Percent Distribution                NaN      Bay County, Florida

In [8]:
#Moving Median Income Values
fl_18_df['number'] = fl_18_df["2018 Median Income"].where(fl_18_df.index.isin(filter_num_plus))

fl_18_df['number'] = fl_18_df['number'].ffill()

#fl_18_df = fl_18_df.loc[~fl_18_df['2018 Median Income']== np.nan]

fl_18_df = fl_18_df.loc[~fl_18_df['2018 Median Income'].isnull()]

fl_18_df.head(15)

              County 2018 Median Income                    county   number
2           Estimate             97,048   Alachua County, Florida   97,048
4           Estimate             97,048   Alachua County, Florida   97,048
6           Estimate             49,078   Alachua County, Florida   97,048
9           Estimate              8,625     Baker County, Florida    8,625
11          Estimate              8,625     Baker County, Florida    8,625
13          Estimate             61,769     Baker County, Florida    8,625
16          Estimate             70,199       Bay County, Florida   70,199
18          Estimate             70,199       Bay County, Florida   70,199
20          Estimate             51,829       Bay County, Florida   70,199
23          Estimate              8,993  Bradford County, Florida    8,993
25          Estimate              8,993  Bradford County, Florida    8,993
27          Estimate             46,197  Bradford County, Florida    8,993
30          Estimate            228,888   Brevard County, Florida  228,888
32          Estimate            228,888   Brevard County, Florida  228,888
34          Estimate             54,359   Brevard County, Florida  228,888

In [9]:
#Drop unnecessary columns
fl_18_df = fl_18_df.reset_index()

fl_18_df = fl_18_df.drop(["index","County","number"], axis=1)

fl_18_df.head(15)

   2018 Median Income                    county
0              97,048   Alachua County, Florida
1              97,048   Alachua County, Florida
2              49,078   Alachua County, Florida
3               8,625     Baker County, Florida
4               8,625     Baker County, Florida
5              61,769     Baker County, Florida
6              70,199       Bay County, Florida
7              70,199       Bay County, Florida
8              51,829       Bay County, Florida
9               8,993  Bradford County, Florida
10              8,993  Bradford County, Florida
11             46,197  Bradford County, Florida
12            228,888   Brevard County, Florida
13            228,888   Brevard County, Florida
14             54,359   Brevard County, Florida

In [10]:
#Only keep every third row (actual median income value)

fl_18_df = fl_18_df.iloc[2::3]

fl_18_df.head(15)

   2018 Median Income                     county
2              49,078    Alachua County, Florida
5              61,769      Baker County, Florida
8              51,829        Bay County, Florida
11             46,197   Bradford County, Florida
14             54,359    Brevard County, Florida
17             57,333    Broward County, Florida
20             38,609    Calhoun County, Florida
23             49,225  Charlotte County, Florida
26             41,424     Citrus County, Florida
29             62,653       Clay County, Florida
32             65,675    Collier County, Florida
35             44,491   Columbia County, Florida
38             35,057     DeSoto County, Florida
41             38,237      Dixie County, Florida
44             53,473      Duval County, Florida

In [11]:
#Only keep county names
fl_18_df["county"] = fl_18_df["county"].str.replace(", Florida", "")

fl_18_df.head(10)

   2018 Median Income            county
2              49,078    Alachua County
5              61,769      Baker County
8              51,829        Bay County
11             46,197   Bradford County
14             54,359    Brevard County
17             57,333    Broward County
20             38,609    Calhoun County
23             49,225  Charlotte County
26             41,424     Citrus County
29             62,653       Clay County

In [12]:
#Reset index and rename column
fl_18_df = fl_18_df.reset_index(drop=True)

fl_18_df.rename(columns={"county":"County"},inplace=True)

fl_18_df.head(15)

   2018 Median Income            County
0              49,078    Alachua County
1              61,769      Baker County
2              51,829        Bay County
3              46,197   Bradford County
4              54,359    Brevard County
5              57,333    Broward County
6              38,609    Calhoun County
7              49,225  Charlotte County
8              41,424     Citrus County
9              62,653       Clay County
10             65,675    Collier County
11             44,491   Columbia County
12             35,057     DeSoto County
13             38,237      Dixie County
14             53,473      Duval County

In [13]:
fl_Clean18_df = fl_18_df.set_index("County")

fl_Clean18_df.head(10)

                 2018 Median Income
County
Alachua County               49,078
Baker County                 61,769
Bay County                   51,829
Bradford County              46,197
Brevard County               54,359
Broward County               57,333
Calhoun County               38,609
Charlotte County             49,225
Citrus County                41,424
Clay County                  62,653

**2019 Data**

In [15]:
print("Shape:",fl_raw_19_df.shape)
display(fl_raw_19_df.columns)
display(fl_raw_19_df.head(10))

Shape: (469, 2)

Index(['Label (Grouping)', 'HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households'], dtype='object')

,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households
0,"Alachua County, Florida",NaN
1,Number,NaN
2,Estimate,"97,995"
3,Percent Distribution,NaN
4,Estimate,"97,995"
5,Median income (dollars),NaN
6,Estimate,"49,689"
7,"Baker County, Florida",NaN
8,Number,NaN
9,Estimate,"8,693"

In [16]:
#Rename 2019 Columns
fl_19_df = fl_raw_19_df.rename(columns={"Label (Grouping)":"County","HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households":"2019 Median Income"})
fl_19_df.head(15)

                         County 2019 Median Income
0       Alachua County, Florida                NaN
1                        Number                NaN
2                      Estimate             97,995
3          Percent Distribution                NaN
4                      Estimate             97,995
5       Median income (dollars)                NaN
6                      Estimate             49,689
7         Baker County, Florida                NaN
8                        Number                NaN
9                      Estimate              8,693
10         Percent Distribution                NaN
11                     Estimate              8,693
12      Median income (dollars)                NaN
13                     Estimate             63,275
14          Bay County, Florida                NaN

In [17]:
#Moving County names
fl_19_df['county'] = fl_19_df['County'].where(fl_19_df['County'].str.contains('County'))

fl_19_df['county'] = fl_19_df['county'].ffill()

fl_19_df = fl_19_df.loc[~fl_19_df['County'].str.contains('County')]

#Moving values
filter_number = fl_19_df["County"].str.contains("Number")

filter_num_true = filter_number.loc[filter_number].index

filter_num_plus = filter_number.loc[filter_number].index+1

value = fl_19_df.loc[filter_num_plus,["2019 Median Income"]]

#Moving Median Income Values
fl_19_df['number'] = fl_19_df["2019 Median Income"].where(fl_19_df.index.isin(filter_num_plus))

fl_19_df['number'] = fl_19_df['number'].ffill()

fl_19_df = fl_19_df.loc[~fl_19_df['2019 Median Income'].isnull()]

#Drop unnecessary columns
fl_19_df = fl_19_df.reset_index()

fl_19_df = fl_19_df.drop(["index","County","number"], axis=1)

#Only keep every third row (actual median income value)

fl_19_df = fl_19_df.iloc[2::3]

fl_19_df.head(15)

#Only keep county names
fl_19_df["county"] = fl_19_df["county"].str.replace(", Florida", "")

#Reset index and rename column
fl_19_df = fl_19_df.reset_index(drop=True)

fl_19_df.rename(columns={"county":"County"},inplace=True)

fl_Clean19_df = fl_19_df.set_index("County")

fl_Clean19_df.head(15)

                 2019 Median Income
County
Alachua County               49,689
Baker County                 63,275
Bay County                   54,316
Bradford County              45,921
Brevard County               56,775
Broward County               59,547
Calhoun County               38,568
Charlotte County             51,499
Citrus County                44,237
Clay County                  65,740
Collier County               69,653
Columbia County              46,494
DeSoto County                35,438
Dixie County                 39,828
Duval County                 55,807

**2020 Data**

In [35]:
print("Shape:",fl_raw_20_df.shape)
display(fl_raw_20_df.columns)
display(fl_raw_20_df.head(10))

Shape: (469, 2)

Index(['Label (Grouping)', 'HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households'], dtype='object')

,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households
0,"Alachua County, Florida",NaN
1,Number,NaN
2,Estimate,"101,979"
3,Percent Distribution,NaN
4,Estimate,"101,979"
5,Median income (dollars),NaN
6,Estimate,"50,089"
7,"Baker County, Florida",NaN
8,Number,NaN
9,Estimate,"8,828"

In [37]:
#Rename 2020 Columns
fl_20_df = fl_raw_20_df.rename(columns={"Label (Grouping)":"County","HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households":"2020 Median Income"})
fl_20_df.head(15)

                         County 2020 Median Income
0       Alachua County, Florida                NaN
1                        Number                NaN
2                      Estimate            101,979
3          Percent Distribution                NaN
4                      Estimate            101,979
5       Median income (dollars)                NaN
6                      Estimate             50,089
7         Baker County, Florida                NaN
8                        Number                NaN
9                      Estimate              8,828
10         Percent Distribution                NaN
11                     Estimate              8,828
12      Median income (dollars)                NaN
13                     Estimate             62,299
14          Bay County, Florida                NaN

In [39]:
#Moving County names
fl_20_df['county'] = fl_20_df['County'].where(fl_20_df['County'].str.contains('County'))

fl_20_df['county'] = fl_20_df['county'].ffill()

fl_20_df = fl_20_df.loc[~fl_20_df['County'].str.contains('County')]

#Moving values
filter_number = fl_20_df["County"].str.contains("Number")

filter_num_true = filter_number.loc[filter_number].index

filter_num_plus = filter_number.loc[filter_number].index+1

value = fl_20_df.loc[filter_num_plus,["2020 Median Income"]]

#Moving Median Income Values
fl_20_df['number'] = fl_20_df["2020 Median Income"].where(fl_20_df.index.isin(filter_num_plus))

fl_20_df['number'] = fl_20_df['number'].ffill()

fl_20_df = fl_20_df.loc[~fl_20_df['2020 Median Income'].isnull()]

#Drop unnecessary columns
fl_20_df = fl_20_df.reset_index()

fl_20_df = fl_20_df.drop(["index","County","number"], axis=1)

#Only keep every third row (actual median income value)

fl_20_df = fl_20_df.iloc[2::3]

fl_20_df.head(15)

#Only keep county names
fl_20_df["county"] = fl_20_df["county"].str.replace(", Florida", "")

#Reset index and rename column
fl_20_df = fl_20_df.reset_index(drop=True)

fl_20_df.rename(columns={"county":"County"},inplace=True)

fl_Clean20_df = fl_20_df.set_index("County")

fl_Clean20_df.head(15)

                 2020 Median Income
County
Alachua County               50,089
Baker County                 62,299
Bay County                   56,483
Bradford County              43,580
Brevard County               59,359
Broward County               60,922
Calhoun County               38,037
Charlotte County             52,724
Citrus County                45,689
Clay County                  68,657
Collier County               70,217
Columbia County              44,818
DeSoto County                36,360
Dixie County                 41,674
Duval County                 56,769

**2021 Data**

In [42]:
print("Shape:",fl_raw_21_df.shape)
display(fl_raw_21_df.columns)
display(fl_raw_21_df.head(10))

Shape: (469, 2)

Index(['Label (Grouping)', 'HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households'], dtype='object')

,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households
0,"Alachua County, Florida",NaN
1,Number,NaN
2,Estimate,"105,003"
3,Percent Distribution,NaN
4,Estimate,"105,003"
5,Median income (dollars),NaN
6,Estimate,"53,314"
7,"Baker County, Florida",NaN
8,Number,NaN
9,Estimate,"8,532"

In [46]:
#Rename 2021 Columns
fl_21_df = fl_raw_21_df.rename(columns={"Label (Grouping)":"County","HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Households":"2021 Median Income"})
fl_21_df.head(15)

                         County 2021 Median Income
0       Alachua County, Florida                NaN
1                        Number                NaN
2                      Estimate            105,003
3          Percent Distribution                NaN
4                      Estimate            105,003
5       Median income (dollars)                NaN
6                      Estimate             53,314
7         Baker County, Florida                NaN
8                        Number                NaN
9                      Estimate              8,532
10         Percent Distribution                NaN
11                     Estimate              8,532
12      Median income (dollars)                NaN
13                     Estimate             63,860
14          Bay County, Florida                NaN

In [48]:
#Moving County names
fl_21_df['county'] = fl_21_df['County'].where(fl_21_df['County'].str.contains('County'))

fl_21_df['county'] = fl_21_df['county'].ffill()

fl_21_df = fl_21_df.loc[~fl_21_df['County'].str.contains('County')]

#Moving values
filter_number = fl_21_df["County"].str.contains("Number")

filter_num_true = filter_number.loc[filter_number].index

filter_num_plus = filter_number.loc[filter_number].index+1

value = fl_21_df.loc[filter_num_plus,["2021 Median Income"]]

#Moving Median Income Values
fl_21_df['number'] = fl_21_df["2021 Median Income"].where(fl_21_df.index.isin(filter_num_plus))

fl_21_df['number'] = fl_21_df['number'].ffill()

fl_21_df = fl_21_df.loc[~fl_21_df['2021 Median Income'].isnull()]

#Drop unnecessary columns
fl_21_df = fl_21_df.reset_index()

fl_21_df = fl_21_df.drop(["index","County","number"], axis=1)

#Only keep every third row (actual median income value)

fl_21_df = fl_21_df.iloc[2::3]

fl_21_df.head(15)

#Only keep county names
fl_21_df["county"] = fl_21_df["county"].str.replace(", Florida", "")

#Reset index and rename column
fl_21_df = fl_21_df.reset_index(drop=True)

fl_21_df.rename(columns={"county":"County"},inplace=True)

fl_Clean21_df = fl_21_df.set_index("County")

fl_Clean21_df.head(15)

                 2021 Median Income
County
Alachua County               53,314
Baker County                 63,860
Bay County                   60,473
Bradford County              48,803
Brevard County               63,632
Broward County               64,522
Calhoun County               38,098
Charlotte County             57,887
Citrus County                48,664
Clay County                  74,059
Collier County               75,543
Columbia County              47,750
DeSoto County                39,945
Dixie County                 44,287
Duval County                 59,541

**Join DataFrames**

In [53]:
fl_county_income_df = fl_Clean18_df.join(fl_Clean19_df).join(fl_Clean20_df).join(fl_Clean21_df)

print("Shape:",fl_county_income_df.shape)
fl_county_income_df.head(10)

Shape: (67, 4)

,2018 Median Income,2019 Median Income,2020 Median Income,2021 Median Income
County,,,,
Alachua County,"49,078","49,689","50,089","53,314"
Baker County,"61,769","63,275","62,299","63,860"
Bay County,"51,829","54,316","56,483","60,473"
Bradford County,"46,197","45,921","43,580","48,803"
Brevard County,"54,359","56,775","59,359","63,632"
Broward County,"57,333","59,547","60,922","64,522"
Calhoun County,"38,609","38,568","38,037","38,098"
Charlotte County,"49,225","51,499","52,724","57,887"
Citrus County,"41,424","44,237","45,689","48,664"
Clay County,"62,653","65,740","68,657","74,059"

In [59]:
#Export results to .csv
file_name = "fl_county_income.csv"
file_path = Path(f"../../../../data/processed_data/{file_name}")

if file_path.exists():
    print("File already exists. Overwriting file.")
    file_path.unlink()

if not file_path.exists():
    print("Creating file...")
    fl_county_income_df.to_csv(file_path, index=True)
    print(f"File saved as {file_name}")

#fl_county_income_df.to_csv("fl_county_income.csv", index=True)

Creating file...
File saved as fl_county_income.csv